### ISSUE TITLE
taskset: failed to parse CPU list

### ISSUE THREAD

**Issue by hr283** [aquaskyline/Clairvoyante#11]
Hello,

Thanks very much for this tool, I'm keen to see whether we can get improved SNV calling for our WGS projects. 
I installed Clairvoyante yesterday and am trying to run it on our computing cluster (so I followed the instructions in the readme for 'not having root access'). I am trying to call variants across chr22 in ONT data using the following script:

```
#!/bin/bash
#$ -V
#$ -S /bin/bash
#$ -cwd
#$ -pe shmem 4

set -e
set -x

module load python/3.5.2-gcc5.4.0
module load gcc/5.4.0
source ~/tf1.8_py/bin/activate
cd ~/Clairvoyante/

python clairvoyante/callVarBamParallel.py \
       --chkpnt_fn trainedModels/fullv3-ont-ngmlr-hg001-hg19/learningRate1e-3.epoch999 \
       --ref_fn ../references/hs37d5lam.fasta \
       --bam_fn ../bams/germline-pass-all-minimap2-md-chr22.bam \
       --sampleName germline-minimap2-chr22 \
       --output_prefix ../calling/germline-minimap-chr22 \
       --threshold 0.3 \
       --minCoverage 4 \
       --tensorflowThreads 4 \
       --pypy ../apps/pypy-5.8-linux_x86_64-portable/bin/pypy \
       --samtools ../apps/samtools/1.4.1/bin/samtools \
       > commands.sh
export CUDA_VISIBLE_DEVICES=""

grep 'ctgName 22' commands.sh > commands_subset.sh
chmod 755 commands_subset.sh
./commands_subset.sh
```

I get the following error:

```
taskset: failed to parse CPU list: %s
Delay 0 seconds before starting variant calling ...
callVar.py exited with exceptions. Exiting...
```

Having looked at callVarBam.py I wondered whether this might be a but because I can't see where the variable cpuSet is used (if I'm remembering correctly), but equally realise it's more likely that I'm missing something!
Apologies if I've missed some crucial/useful information out of this post.

Many thanks for your help,
Hannah

**Comment by aquaskyline** [comment]
Bug fixed, please pull the latest code. Thank you.

**Comment by hr283** [comment]
Thank you - working now

**Comment by BryanHepworth** [comment]
Ahh... this was going to be my next question as I've just bumped up against the very same error!

python ../clairvoyante/callVarBam.py --chkpnt_fn ../trainedModels/fullv3-illumina-novoalign-hg001+hg002-hg38/learningRate1e-3.epoch500 --bam_fn ../testingData/chr21/chr21.bam --ref_fn ../testingData/chr21/chr21.fa --bed_fn ../testingData/chr21/chr21.bed --call_fn chr21_calls.vcf --ctgName chr21
Delay 3 seconds before starting variant calling ...
taskset: failed to parse CPU list: %s
callVar.py exited with exceptions. Exiting...
samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1
[root@tomaini training]# samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1

Pulled new version and it all functions here just fine now too 

Thank you

Bryan

**Comment by aquaskyline** [comment]
@BryanHepworth Thanks.
