### ISSUE TITLE
FILTER and INFO fields

### ISSUE THREAD

**Issue by ghost** [aquaskyline/Clairvoyante#18]
Hello,
it seems clairvoyante tends not to fill those 2 filters. Is it the expected behaviour? 

```
A_Seg296	7630007	.	A	C	999	.	.	GT:GQ:DP:AF	0/1:999:354:0.4972
A_Seg296	7630172	.	AC	A	999	.	.	GT:GQ:DP:AF	0/1:999:299:0.5485
```

Or does it mean Clairvoyante did not understand what kind of variant those are? 
Thank you

**Comment by aquaskyline** [comment]
Those two fields could be filled by post-procession tools, such as filtration, etc.

**Comment by ghost** [comment]
Thanks! was just double checking
