### ISSUE TITLE
genotype and estimated allele frequency

### ISSUE THREAD

**Issue by axgraf** [aquaskyline/Clairvoyante#19]
Hi,
I have a question regarding the genotype and estimated allele frequency. I have several lines showing a genotype of 1/1 with an allele frequency of 0.0000
Example:

incorrect frequency:
chr10   71861  .       C       G       47      .       .       GT:GQ:DP:AF     1/1:47:5:0.0000
chr10   71862   .       C       T       33      .       .       GT:GQ:DP:AF     1/1:33:2:0.0000

I also get correctly estimated frequencies:
chr10   71517   .       C       T       287     .       .       GT:GQ:DP:AF     1/1:287:37:0.7568

IGV of incorrect frequency (chr10   71861):
![hom_c_g](https://user-images.githubusercontent.com/16762600/55548580-0e086f00-56d4-11e9-8378-ab168f27472d.png)

Looking in the IGV, it shows that the genotype is correct but the frequency is 0. The read depth also doesn't reflect the number of reads at that position. 

IGV of correct frequency (chr10   71517) :
![correct_frequency](https://user-images.githubusercontent.com/16762600/55549623-9720a580-56d6-11e9-8de7-36d94707f979.png)

I even don't see any big differences in the mapping for correctly called frequencies.
Is there anything I have to consider/change?

Thank you
Alex

**Comment by axgraf** [comment]
I unfortunately forgot to mention that the dataset above was basecalled using flipflop.
I just have seen at @chaklim's github that there exists a successor to Clairvoyante, named Clair. By reading the through I have seen that there exists a model for flip-flop basecalled reads. So might it be due to the flip flop base caller? I will give Clair a try, to see if that might resolve the problems, or what do you think? If you need some test data, I can put something together...
Thanks
Alex

**Comment by axgraf** [comment]
Hi again,
I have tested Clair and Clairvoyante now. My current workflow: The promethION data is basecalled using Flappie with flip-flop support. Then the data is mapped using NGMLR to the human reference genome. Then I run for Clairvoyante:

`callVarBamParallel.py --chkpnt_fn trainedModels/fullv3-ont-ngmlr-hg001-hg19/learningRate1e-3.epoch999 --ref_fn hg19_chromosomes.fa --bam_fn sample1.ngmlr.sorted.bam --sampleName sample1 --output_prefix sample1 --threshold 0.1 --minCoverage 5 --tensorflowThreads 4
`

For Clair I only exchanged the model to  ` --chkpnt_fn models/ont/r94-flipflop/model`

For that sample I also have SNPs from Illumina to compare with. 
I'm now really confused as the output is quite strange to me.

If I look at a SNP position identified by Illumina I get the following picture from IGV for the nanopore reads:

![illumina_snp](https://user-images.githubusercontent.com/16762600/55623052-1f1fb180-57a2-11e9-9438-35b512151d0b.png)


And for Clairvoyante and Clair (using the flip-flop model) I receive follwing results:

Illumina SNP:
chr1       10274695        .       T       C       222     .    GT:PL:GQ        1/1:255,148,0:99 

Clairvoyante:
chr1    10274684        .       A       C       49      .       .       GT:GQ:DP:AF     1/1:49:1:0.0000
**chr1    10274695        .       T       G       30      .       .       GT:GQ:DP:AF     0/1:30:1:0.0000**
chr1    10274702        .       G       T       69      .       .       GT:GQ:DP:AF     1/1:69:1:0.0000

Clair:
nothing found at that position

The Clairvoyante output is actually correct, as there is no 'G' (0.000 allele frequency) at that position but I'm lacking the clear homozygote 'C' in the output.
To make things clear I also get correctly called SNPs from both Clairvoyante and Clair, but it seems that they are missing some genotypes. 
Also I could not see any pattern when that happens. Any ideas?

Thank you again

Alex

**Comment by chaklim** [comment]
After looking into your issue, the main reason why the output is not as expected is because of the commit https://github.com/aquaskyline/Clairvoyante/pull/9.

In the current implementation of Clairvoyante / Clair, only primary reads are considered. As you can see, the read depths in chr10 71861 and chr1 10274695 in the vcf output is obviously smaller (5 and 1 respectively) than the IGV images above.

You may revert the changes in the aforementioned commit and give it a try. However, you may suffer from issues stated in
https://github.com/aquaskyline/Clairvoyante/issues/6
https://github.com/aquaskyline/Clairvoyante/issues/7
