### ISSUE TITLE
Score distribution

### ISSUE THREAD

**Issue by ghost** [aquaskyline/Clairvoyante#23]
Hello (it's me again sorry). 
How does Clairvoyante compute its score exactly? I have a very intriguing pattern of score distribution, with no score between 501 and 998. 
Is it a "normal" pattern of score distribution? 
Here on 4 of my samples.
Thanks a lot
![score svg](https://user-images.githubusercontent.com/23341393/56142306-b7861500-5f9e-11e9-8a20-abb384ad367b.png)

**Comment by aquaskyline** [comment]
Yes, it's normal. Using the current scoring scheme in Clairvoyante, the distribution is expected. Now we cap the maximum score to 999. One can cap it to 500 if considering the number of variants with a score between 500 to 999 is small.
