### ISSUE TITLE
conda installation intervaltree

### ISSUE THREAD

**Issue by wdecoster** [aquaskyline/Clairvoyante#24]
I noticed that intervaltree is available on conda now, or is not the right version? See https://anaconda.org/conda-forge/intervaltree

Also note that recent versions of conda use `conda activate <env>` rather than `source activate <env>`.

**Comment by fritzsedlazeck** [comment]
Yeah you need the interval tree from pip install. 
Thanks
Fritz

**Comment by aquaskyline** [comment]
We can install intervaltree for python but not pypy.

**Comment by aquaskyline** [comment]
README updated using ```source activate```
