### ISSUE TITLE
Suggesting slight improvement error when no contig specified

### ISSUE THREAD

**Issue by ghost** [aquaskyline/Clairvoyante#25]
Hello, 
if no contig list is specified and you are not working with the "default", then Clairvoyante will not call any variant because it doesn't know where to call them. So far so good. 
I think it would be useful, however, if it could throw a warning message such as "specify a contig list or use the --inclureallcontigs". 

It took me quite a long while to figure out why I was not getting any output.

**Comment by aquaskyline** [comment]
Resolved in Clair.
