### ISSUE TITLE
trainedModels directory

### ISSUE THREAD

**Issue by yangxiaofeill** [aquaskyline/Clairvoyante#32]
Hi,
    I have installed Clairvoyante by anaconda2. However, I cannot find the trainedModels directory in the anaconda2 directory. Also, it cannot be found on github.  So, I'd like to know where can I download the traninedModels? In addition, If I have a new Bam file, should I need to train a new model or just use the trained models?

Best
Xiaofei

**Comment by aquaskyline** [comment]
Please follow the README.md
