### ISSUE TITLE
Failed to tabix the generated vcf files

### ISSUE THREAD

**Issue by alex538** [aquaskyline/Clairvoyante#37]
Hi,
I've got problem combining the generated vcf files into one.
I followed the instructions using vcfcat,vcfstreamsort, and bgziptabix. But I got the following error: Unsorted positions on sequence #1: 103549237 followed by 10000678
And if I use tabix directly on the vcf files generated, the tabix fails. Does anyone know what causes the problem?

**Comment by aquaskyline** [comment]
Unable to tell what was wrong without the culprit VCF file. Could you please copy and paste here the VCF records at 103549237 and 10000678, as well as 10 flanking records of the two sites?

**Comment by alex538** [comment]
Here are the vcf records.

chr10	103540571	.	C	T	257	.	.	GT:GQ:DP	0/1:257:47
chr10	103540586	.	A	G	210	.	.	GT:GQ:DP	0/1:210:45
chr10	103540684	.	GA	G	213	.	.	GT:GQ:DP	0/1:213:39
chr10	103540789	.	C	T	246	.	.	GT:GQ:DP	0/1:246:42
chr10	103543641	.	G	A	261	.	.	GT:GQ:DP	0/1:261:34
chr10	103545244	.	G	T	200	.	.	GT:GQ:DP	0/1:200:39
chr10	103547827	.	T	G	448	.	.	GT:GQ:DP	1/1:448:41
chr10	103547967	.	G	A	273	.	.	GT:GQ:DP	0/1:273:39
chr10	103548132	.	T	C	999	.	.	GT:GQ:DP	1/1:999:49
chr10	103548331	.	C	CT	105	.	.	GT:GQ:DP	1/1:105:70
chr10	103549106	.	C	G	999	.	.	GT:GQ:DP	1/1:999:51
chr10	103549237	.	T	A	271	.	.	GT:GQ:DP	0/1:271:35
chr10	10000678	.	C	T	232	.	.	GT:GQ:DP	0/1:232:40
chr10	10000703	.	C	CGTGT	91	.	.	GT:GQ:DP	0/1:91:60
chr10	10000862	.	T	C	265	.	.	GT:GQ:DP	0/1:265:30
chr10	10000931	.	A	G	265	.	.	GT:GQ:DP	0/1:265:45
chr10	10001196	.	T	A	213	.	.	GT:GQ:DP	0/1:213:43
chr10	10001623	.	A	T	251	.	.	GT:GQ:DP	0/1:251:35
chr10	10001745	.	G	T	143	.	.	GT:GQ:DP	1/1:143:35
chr10	10001859	.	C	T	235	.	.	GT:GQ:DP	0/1:235:29
chr10	10002770	.	ATG	A	134	.	.	GT:GQ:DP	0/1:134:37
chr10	10002942	.	T	C	237	.	.	GT:GQ:DP	0/1:237:47
chr10	10003182	.	A	G	280	.	.	GT:GQ:DP	0/1:280:53
