### ISSUE TITLE
callVarBam.py fails with taskset: failed to set pid 0's affinity: Invalid argument

### ISSUE THREAD

**Issue by jazberna1** [aquaskyline/Clairvoyante#38]
Hello,

I have noticed that some of the executions of callVarBam.py fail with this error:

`callVarBam.py fails with taskset: failed to set pid 0's affinity: Invalid argument`

At least in my case all the executions are the same with the exception of the --ctgStart ,  --ctgEnd and the --call_fn params.

Also I have noticed that removing the --threads option fixes the issue. Is there any reason for this?

Thanks so much
Jorge

**Comment by aquaskyline** [comment]
Do you have 'taskset' in your running environment?
