### ISSUE TITLE
SNV report is not consistent with the bam file

### ISSUE THREAD

**Issue by HJTsai** [aquaskyline/Clairvoyante#39]
Hi,

![image](https://user-images.githubusercontent.com/49969700/64059414-c3d9da00-cbee-11e9-8a64-27c3864ea02c.png)
![image](https://user-images.githubusercontent.com/49969700/64059428-03a0c180-cbef-11e9-90b3-ce2853cc02c4.png)
These figures show a INDEL was reported, however there are no INDEL in the bam file.

Could you help us to resolve this problem?

Thanks 

HJ Tsai

**Comment by aquaskyline** [comment]
It's possible that even without read support, the network thinks a variant should exist, the AF will be 0 for these cases. You might want to remove all the calls with 0 AF before using them for analysis.

Please also try Clair, which is a newer version of Clariovyante, https://github.com/HKU-BAL/Clair.
