### ISSUE TITLE
Does the pacBio model you have trained can be used for PacBio CCS reads?

### ISSUE THREAD

**Issue by ydLiu-HIT** [aquaskyline/Clairvoyante#42]
Hi, 
I want to detect SNP and Indels on PacBio CCS read BAM (ftp://ftp.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/PacBio_SequelII_CCS_11kb/HG002.SequelII.pbmm2.hs37d5.whatshap.haplotag.RTG.10x.trio.bam), is there any model you have trained can be used for calling, or I have the need to train a new model for PacBio CCS reads.

Best

**Comment by aquaskyline** [comment]
Resolved in Clair.
