### ISSUE TITLE
GPU conda install docs remove Clairvoyante

### ISSUE THREAD

**Issue by CanWood** [aquaskyline/Clairvoyante#44]
Hi folks!

I'm just installing the GPU version of Clairvoyante using the "Using bioconda" instructions and have found that the  `conda remove tensorflow` results in the following:

```
The following packages will be REMOVED:

    clairvoyante: 1.02-1       bioconda
    tensorflow:   1.9.0-py27_0 conda-forge
```
I'm presuming that after the subsequent `conda install tensorflow-gpu`, a `conda install -c bioconda clairvoyante` would do the job.  I'll test now but thought I'd flag it in case the development team believes my approach or findings are incorrect and I'm heading down the wrong path.

Cheers

**Comment by CanWood** [comment]
Hi again,

I followed the steps I said I'd try and gave the `demoRun.py` a go, watched system resource use with `nvidia-smi` and the GPUs are untouched.   I had a look at the environment and both `tensorflow` and `tensorflow-gpu` seem to be in there:

```
$ conda list -n clairvoyante-conda-env |grep tensorflow
tensorflow                1.9.0                    py27_0    conda-forge
tensorflow-base           2.0.0           gpu_py27h356bb79_0  
tensorflow-estimator      2.0.0              pyh2649769_0  
tensorflow-gpu            1.9.0                hf154084_0 
```

I'll step back from suggesting next steps as clearly my approach hasn't worked and I'd best not continue further down the wrong path. Any tips, troubleshooting steps, or corrections would be welcomed.

Thanks!

**Comment by aquaskyline** [comment]
If you are just using Clairvoyante for variant calling, please stay with the CPU version. For model training, an installation from scratch instead of using conda is suggested.
