### ISSUE TITLE
How is the QUAL metric calculated? 

### ISSUE THREAD

**Issue by flashton2003** [aquaskyline/Clairvoyante#45]
Hello,

I'm curious as to how the QUAL metric is calculated, and how it should be interpreted?

From my limited analysis, it seems that only variants with a QUAL of 999 should be taken as high quality variants. Does this seem overly stringent?

Thanks,

Phil

**Comment by aquaskyline** [comment]
QUAL is calculated as the distance between the best and second-best result. Higher score -> larger distance -> more reliable the result is.

BTW, you might want to use the new version at https://github.com/HKU-BAL/Clair. The quality calculation is more reboust in the new version.

**Comment by flashton2003** [comment]
Thank you! I'll check out Clair.
