### ISSUE TITLE
Check that BAM is indexed

### ISSUE THREAD

**Issue by flashton2003** [aquaskyline/Clairvoyante#46]
Hello,

Just a small suggestion, but currently, if the BAM file is not indexed, clairvoyante produces 100 lines of error traceback, with this comment at the top.

```
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.
No read has been process, either the genome region you specified has no read cover, or please check the correctness of your BAM input (/home/ubuntu/tm_data/replimune/variant_calling/2020.04.02/RH018A_NGS_Sequence_Data/RH018A_NGS_Sequence_Data.primary_aln.bam).
```

Could I suggest that you add an explicit check for the index and return a more easily comprehensible error if it isn't there.

Best,

Phil

**Comment by aquaskyline** [comment]
Improved in Clair.
