### ISSUE TITLE
PyPy

### ISSUE THREAD

**Issue by sledford921** [aquaskyline/Clairvoyante#47]
Hello! So whenever I try to run something along the lines of the sample mentioned in the instructions:

cd training
python ../clairvoyante/callVarBam.py \
       --chkpnt_fn ../trainedModels/fullv3-illumina-novoalign-hg001+hg002-hg38/learningRate1e-3.epoch500 \
       --bam_fn ../testingData/chr21/chr21.bam \
       --ref_fn ../testingData/chr21/chr21.fa \
       --bed_fn ../testingData/chr21/chr21.bed \
       --call_fn chr21_calls.vcf \
       --ctgName chr21

I keep running into this error: 

Error: pypy executable not found

Do you know what might be causing this? Thanks a ton! 

-Marshall

**Comment by aquaskyline** [comment]
You need to have pypy installed. Please refer to the readme for me details.

You may also want to try out the latest version at https://github.com/HKU-BAL/Clair/
