### ISSUE TITLE
BAM:the genome region you specified has no read cover

### ISSUE THREAD

**Issue by shiying-sxu** [aquaskyline/Clairvoyante#49]
<_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'> No read has been process, either the genome region you specified has no read cover, or please check the correctness of your BAM input (../testingData/chr21/chr21.bam).

how can i sove this problem?
thankyou!

**Comment by aquaskyline** [comment]
please switch to using Clair or Clair3.

**Comment by shiying-sxu** [comment]
> please switch to using Clair or Clair3.
This happened when an error was reported when running the PrepDataBeforeDemo.sh command. How do I switch?
