### ISSUE TITLE
PASS flag for SNP and VCF header

### ISSUE THREAD

**Issue by fritzsedlazeck** [aquaskyline/Clairvoyante#5]
For certain applications it would be helpful to provide a PASS flag for trustworthy SNPs.

Also please consider to extend the VCF header with e.g. chromosome names and length. 
Thanks
Fritz

**Comment by aquaskyline** [comment]
No problem. Will add a function for adding the PASS flag and headers.

**Comment by aquaskyline** [comment]
add contig tags in header; add PASS and LowQual filter tag if --qual is set for callVarBamParallel.py or callVarBam.py
