### ISSUE TITLE
No output in commands.sh

### ISSUE THREAD

**Issue by zya226** [aquaskyline/Clairvoyante#50]
Hi,

I tried to run "python /Clairvoyante/clairvoyante/callVarBamParallel.py --chkpnt_fn /fdb/Clairvoyante/trainedModels/fullv3-illumina-novoalign-hg001+hg002-hg38/learningRate1e-3.epoch500 --bam_fn sorted.winnowmap.aligned.bam --ref_fn /data/zhangy61/Avi_Nath/Wenxue_Li/reference_h38.fa --bed_fn /data/zhangy61/Avi_Nath/Wenxue_Li/HERVK.bed.changed.bedtools --sampleName Pacbio --output_prefix clairvoyante_pacbio --minCoverage 4 > commands.sh". However, there is no output in commands.sh. Could you please help me look at it?

**Comment by aquaskyline** [comment]
Thanks for trying out, please switch to using Clair or Clair3.
