### ISSUE TITLE
can't call variant using  bam file from minmap2

### ISSUE THREAD

**Issue by MeHelmy** [aquaskyline/Clairvoyante#7]
Clairvoyante doesn't work with bam file resulted from minmap2; 
Aligning command;

`minimap2 -ax map-pb -H -MD -t 10 hs37d5_mainchr.fa subreads.fasta.gz | samtools sort -@ 10 -o subreads.bam -  && samtools index subreads.bam`

Then calling variant;

`clairvoyante.py callVarBam   --chkpnt_fn ./trainedModels/fullv3-pacbio-ngmlr-hg001+hg002+hg003+hg004-hg19/learningRate1e-3.epoch100.learningRate1e-4.epoch200   --bam_fn subreads.bam --ref_fn  hs37d5_mainchr.fa   --minCoverage 2 --ctgName 1   --call_fn 1_vcf.tmp  --threads 2`

Error raised;

```
Delay 9 seconds before starting variant calling ...
Loading model ...
Traceback (most recent call last):
  File "conda3_64/envs/clairvoyante-1.0.0-1/bin/dataPrepScripts/ExtractVariantCandidates.py", line 316, in <module>
    main()
  File "conda3_64/envs/clairvoyante-1.0.0-1/bin/dataPrepScripts/ExtractVariantCandidates.py", line 312, in main
    MakeCandidates(args)
  File "/cconda3_64/envs/clairvoyante-1.0.0-1/bin/dataPrepScripts/ExtractVariantCandidates.py", line 168, in MakeCandidates
    matches.append( (refPos, SEQ[queryPos]) )
IndexError: string index out of range
samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1
ExtractVariantCandidates.py or GetTruth.py exited with exceptions. Exiting...
(clairvoyante-1.0.0-1) -bash-4.1$ samtools view: writing to standard output failed: Broken pipe
```

Thanks

**Comment by aquaskyline** [comment]
could you copy/paste two lines of your minimap2 output

**Comment by aquaskyline** [comment]
I think we found the reason, will return to you later with a fix

**Comment by aquaskyline** [comment]
problem fixed
